base:
  project_name: HPFN
  ckpt_root: ./ckpt
  seed: 7
  lr: 0.0001
  weight_decay: 0.0001
  batch_size: 64
  n_epochs: 200
  num_workers: 8
  gpu_id: 1

dataset:
  datasetName: mosei
  dataPath: ...data/mosei/aligned_50.pkl
  train_mode: regression

model:
  arch: hpf

  bert_pretrained: .../bert-base-uncased

  # ==== input（MOSI）====
  l_input_dim: 768
  a_input_dim: 74
  v_input_dim: 35

  # ==== length====
  l_input_length: 50
  a_input_length: 375
  v_input_length: 500

  # ==== dim & token ====
  proj_input_dim: 128
  token_length: 8        # L
  token_len: 8
  token_dim: 128

  # ==== unimode ====
  cnn_depth: 1
  cnn_kernel_size: 3
  cnn_dilated: true
  proj_dropout: 0.00      # ProjMLP  dropout

  # ==== cross-modal====
  mamba_use: true
  mamba_depth: 1
  mamba_state_dim: 64
  mamba_expand: 2
  mamba_fallback_heads: 8
  mamba_fallback_mlp_ratio: 4

  # ==== Transformer（4L + 1 token）====
  fusion_layer_depth: 1
  fusion_heads: 8
  fusion_mlp_dim: 128
  fusion_dropout: 0.0
  emb_dropout: 0.0

  # ==== CLS and Mean weight ====
  alpha: 0.4   # 0.3

  # ===== =====
  l_proj_dst_dim: 128
  a_proj_dst_dim: 128
  v_proj_dst_dim: 128
  proj_depth: 1
  proj_heads: 8
  proj_mlp_dim: 128

  l_enc_heads: 8
  l_enc_mlp_dim: 128

  AHL_depth: 3
  ahl_heads: 8
  ahl_dim_head: 16
  ahl_droup: 0.0

  fusion_type: cross
